import adapterGhpages from "svelte-adapter-ghpages";
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://svelte.dev/docs/kit/integrations
	// for more information about preprocessors
	preprocess: vitePreprocess(),

	kit: {
		// adapter-auto only supports some environments, see https://svelte.dev/docs/kit/adapter-auto for a list.
		// If your environment is not supported, or you settled on a specific environment, switch out the adapter.
		// See https://svelte.dev/docs/kit/adapters for more information about adapters.
		adapter: adapterGhpages({
			// default options are shown. On some platforms
			// these options are set automatically — see below
			pages: 'build',
			assets: 'build',
			fallback: null,
		}),
        paths: {
			base: '/TomeDuMageNoir'
		},
        prerender: {
            handleHttpError : 'warn',
            entries : [
                "/",
                "/collection",
                "/card/Tourment-d-epines",
                "/card/Meteore-du-desert",
                "/card/Flamme-de-soufre",
                "/card/Baguette_des_courants_d_air",
                "/card/Armure-solide",
                "/card/Sirocco",
                "/card/Souffle_de_la_guerisseuse",
                "/card/Fleur-de-kerloc-h",
                "/card/Graine-des-sables",
                "/card/Graine_dans_le_vent",
                "/card/Petales-tranchants",
                "/card/Cape-galactique",
                "/card/Semee-prodigieuse",
                "/card/Vague-echo",
                "/card/Lumiere-radieuse",
                "/card/Fleur-fractale",
                "/card/Rituel-du-melange",
                "/card/Vent_violent",
                "/card/La-guerisseuse-sylvestre",
                "/card/Rituel-du-zero-absolu",
                "/card/Reflexion-abstruse",
                "/card/Seconde-divisee",
                "/card/Grandes-eaux",
                "/card/Antimatiere",
                "/card/Ere-glaciaire",
                "/card/Etincelle-electrique",
                "/card/Roche",
                "/card/Boule-de-feu",
                "/card/Inspiration-brillante",
                "/card/Vague-du-desert",
                "/card/Robe_du_hurleur",
                "/card/Siecle",
                "/card/Revocation",
                "/card/Lances-de-l-hiver",
                "/card/Minerai-des-temps",
                "/card/Ignition",
                "/card/Mine-souterraine",
                "/card/Rugissement-de-raijin",
                "/card/Fleche-mordante",
                "/card/Chaine-de-foudre",
                "/card/Masque-de-feu",
                "/card/Arbre-anime",
                "/card/La-guerisseuse-de-l-eau",
                "/card/Lame-du-soleil",
                "/card/Blast-temporel",
                "/card/Eblouissement",
                "/card/Soleil-artificiel",
                "/card/Eruption-de-magma",
                "/card/Main-du-desert",
                "/card/Fleche-ardente",
                "/card/Lame-forgee",
                "/card/Meteore-d-ina",
                "/card/Brulure-de-magma",
                "/card/Graine",
                "/card/Etincelle-statique",
                "/card/Minerai-d-or-solaire",
                "/card/Etincelle-de-flamme",
                "/card/Eclair-d-inspiration",
                "/card/Zephyr",
                "/card/Tsunami",
                "/card/Ronces-temporelles",
                "/card/Montre-de-nikola",
                "/card/Baguette-de-druide",
                "/card/Alteration-du-passe",
                "/card/Recuperation-temporelle",
                "/card/Millenaire",
                "/card/Fission",
                "/card/Epee-materialisee",
                "/card/Arc-de-foudre",
                "/card/Brinicle",
                "/card/Couronne-de-la-renonciation",
                "/card/Infiltration-glaciale",
                "/card/Sables-mouvants",
                "/card/Vague-deferlante",
                "/card/Mur-de-roche",
                "/card/Anneau-de-lithomancie",
                "/card/Souffle",
                "/card/Photosynthese",
                "/card/Arbre-mort",
                "/card/Maelstrom",
                "/card/Saut-dans-le-temps",
                "/card/Tornade",
                "/card/Foret-enchantee",
                "/card/Armure-de-druide",
                "/card/Croissance-de-fleur",
                "/card/Flamme-mentale",
                "/card/Rite-de-phase",
                "/card/Colere-de-ra",
                "/card/Fleur-hypnotique",
                "/card/Flamme",
                "/card/Arbre-en-flammes",
                "/card/Bottes-statiques",
                "/card/Graine-germee",
                "/card/Rituel-de-decomposition",
                "/card/Eruption-solaire",
                "/card/Robe-de-yuki-onna",
                "/card/Rituel-pourpre",
                "/card/Mur-du-desert",
                "/card/Appel-de-la-foudre",
                "/card/Sable-fin",
                "/card/Typhon",
                "/card/Infiltration-subtile",
                "/card/Vents_favorables",
                "/card/Lame_d_air",
                "/card/Inception",
                "/card/Vague-de-foudre",
                "/card/Distillation-de-seve",
                "/card/Graine-bourgeonnante",
                "/card/Acceleration-du-temps",
                "/card/Vague-mordante",
                "/card/Hiver-percant",
                "/card/Balayage_puissant",
                "/card/Condensation",
                "/card/Gouttelette",
                "/card/Milliseconde",
                "/card/Rayon-de-lumiere",
                "/card/Fleurs-de-ronces",
                "/card/Coup-de-marteau-divin",
                "/card/Paradoxe-temporel",
                "/card/Mur-de-glace",
                "/card/Flocon-de-neige",
                "/card/Engloutissement",
                "/card/Haute-pression",
                "/card/Renouveau",
                "/card/Rituel-supraconducteur",
                "/card/Arbre-de-pierre",
                "/card/Poing-meteore",
                "/card/Robe-brulante",
                "/card/Rappel-au-present",
                "/card/Avance-rapide",
                "/card/Champ-de-tournesols",
                "/card/Connaissance-de-l-histoire",
                "/card/Ronces-ephemeres",
                "/card/Goutte-d-eau",
                "/card/Vent_tourbillonnant",
                "/card/Retour-a-l-origine",
                "/card/Lame-de-foudre",
                "/card/Flamme-solaire",
                "/card/Cornes-de-druide",
                "/card/Infiltration-temporelle",
                "/card/Armure-d-ecorce",
                "/card/Pluie-de-flammes",
                "/card/Sceptre-galactique",
                "/card/Bastion",
                "/card/Seisme",
                "/card/Flamme-draconique",
                "/card/Rituel-d-exuviation",
                "/card/Roche-friable",
                "/card/Zap",
                "/card/Vague-purificatrice",
                "/card/Roche-ferreuse",
                "/card/Supraconductivite",
                "/card/Invocation-solaire",
                "/card/Souffle-etincelle",
                "/card/Aube",
                "/card/Destin-differe",
                "/card/Projectile-de-flamme",
                "/card/Reforger",
                "/card/Vague-de-flammes",
                "/card/Apercu-du-futur",
                "/card/Volee-aiguisee",
                "/card/Brulure-solaire",
                "/card/Catalyseur-de-soleil",
                "/card/Robe-de-kerloch",
                "/card/Mons-igneus",
                "/card/Rituel-du-savoir",
                "/card/Heaume-galactique",
                "/card/Souffle-de-glace",
                "/card/Chaos",
                "/card/Roche-d-obsidienne",
                "/card/Vents-solaires",
                "/card/Roi-des-arbres",
                "/card/Rite-de-passage",
                "/card/Replique-de-verre",
                "/card/Bobine-tesla",
                "/card/Acceleration-forcee",
                "/card/Ocean-dechaine",
                "/card/Oasis",
                "/card/Fouet-de-feu",
                "/card/Armure-materialisee",
                "/card/Anneau-pourpre",
                "/card/Explosion-solaire",
                "/card/Rituel-des-saisons",
                "/card/Source-prodigieuse",
                "/card/Anneau-du-druide",
                "/card/Acceleration",
                "/card/Meteore-de-cristal",
                "/card/Souffle_de_flammes",
                "/card/Floraison-letale",
                "/card/Temps-destructure",
                "/card/Rituel_du_vide",
                "/card/Souffle-brume",
                "/card/Suppression-dimensionnelle",
                "/card/Foret-hostile",
                "/card/Crocs-du-desert",
                "/card/Rituel-du-zenith",
                "/card/Tonnerre-de-zeus",
                "/card/Maree",
                "/card/Anneau-d-azur",
                "/card/Fleurs-d-arbre",
                "/card/Infusion-florale",
                "/card/Arbre-de-glace",
                "/card/Tonnerre-etourdissant",
                "/card/Echarde-de-glace",
                "/card/Rituel-du-guerrier-mage"
              ]
        }
	}
};

export default config;
