[project]
name = "TomeduMageNoir"
version = "0.1.0"
description = "A basic deckbuilder for the Mage Noir game"
authors = ["Espequair <espequair@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "flask>=3.0.3",
    "requests>=2.32.3",
]
